name: test  # default testing environment name from conda-incubator
dependencies:
  - python=3.13
  - pip
  - setuptools_scm
  - numpy
  - scipy
  - fitsio
  - pip:
    - ducc0
    - coveralls
    - pytest
    - pytest-cov