name: test  # default testing environment name from conda-incubator
dependencies:
  - python=3.11
  - pip
  - setuptools_scm
  - gsl
  - swig
  - healpy
  - numpy
  - scipy
  - pytest
  - pytest-cov
  - flake8
  - pip:
    - ducc0